# Generated by Django 2.0.5 on 2018-05-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_altered', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
